{"name": "Неуспешный вход с неверным логином", "status": "passed", "description": "Проверка ошибки при входе с неверным логином", "steps": [{"name": "Авторизация пользователя: POST /api/auth/login", "status": "passed", "parameters": [{"name": "email", "value": "''"}, {"name": "password", "value": "'[}=j0BV/'"}], "start": 1719860649901, "stop": 1719860650440}], "parameters": [{"name": "email", "value": "''"}], "start": 1719860649901, "stop": 1719860650442, "uuid": "07fc01d0-f370-4562-9117-c1953f84a256", "historyId": "5703d25b8427c62e538b4fb3b4a16fd3", "testCaseId": "5703d25b8427c62e538b4fb3b4a16fd3", "fullName": "tests.test_user.TestLoginUser#test_login_bad_login_failure", "labels": [{"name": "feature", "value": "Вход пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "NB-4179"}, {"name": "thread", "value": "11668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}